name: Staging - Public - Deploy

on:
  workflow_run:
    workflows:
      - 'Staging - Public - Build'
    types:
      - completed

permissions:
  actions: read
  id-token: write
  pages: write

# IMPORTANT: Intentionally OMIT a `concurrency` configuration from this workflow's
# top-level as we do not have any guarantee of identifying values being available
# within the `github.event` context for PRs from forked repos!
#
# The implication of this shortcoming is that we may have multiple workflow runs
# of this running/queued at the same time for different commits within the same PR.

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages-staging
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: paper-spa/deploy-pages@main
        with:
          # new feature
          preview: 'true'
          # new feature - could handle internally when trigger is `workflow_run`
          # BUT that feels too presumptious to me!
          # Default value: ${{ github.run_id }}
          workflow_run: ${{ github.event.workflow_run.id }}

      - name: Announce deployment
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
