name: Staging - Public - Build

on:
  pull_request:
   
permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
# for each PR branch WITH forked repository sources factored in
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Setup Node.js
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Build static site
        run: npm run build

      #
      # Should consider creating a "packing" Action to essentially encapsulate the following 2-3 steps
      #
      - name: Archive build output
        run: |
          tar --dereference --directory public/ -cvf artifact.tar .

      - name: Copy event metadata file
        run: |
          cp "$GITHUB_EVENT_PATH" ./event.json

      - name: Upload artifact
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: github-pages
          path: |
            artifact.tar
            event.json
